name: map_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.5
  geolocator: ^8.0.1
  permission_handler: ^10.2.0
  awesome_dialog: ^3.0.2
  geocoding: ^2.1.0
  flutter_polyline_points: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/ico_laun.jpg"

flutter_native_splash:
  color: "#42a5f5"
  image: "images/ico_splash.jpg"
  android_gravity: center

flutter:

  uses-material-design: true

  assets:
    - images/